Feature/permissions
Jojobass/TaskManager pull request #12
Opened 2023-05-30 06:08 UTC by Jojobass

2023-06-02 06:39 UTC, aleksandr-semenov-dbp requested changes

2023-06-02 06:39 UTC, aleksandr-semenov-dbp commented on main/views.py
> +                return False
Некрасиво, страннее только если написать `if bool_var == True: return True; else: return False`

2023-06-02 07:08 UTC, Jojobass commented on main/views.py
> +                return False
да, согласен)

2023-06-05 16:08 UTC, aleksandr-semenov-dbp approved these changes

2023-06-06 05:32 UTC, Jojobass commented on task_manager/settings.py
> +    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
повторяется в уроке №7 п.4

2023-06-06 08:13 UTC, kirill-gorshkov approved these changes

2023-06-06 08:13 UTC, kirill-gorshkov commented on main/views.py
> +                return False
Можно просто написать return.user.is_staff

2023-06-30 11:23 UTC, closed without merging