Feature/api tests
Jojobass/TaskManager pull request #14
Opened 2023-06-02 09:08 UTC by Jojobass

2023-06-06 07:59 UTC, kirill-gorshkov requested changes

2023-06-06 07:59 UTC, kirill-gorshkov commented on test/test_api.py
> +    def create_user(self, is_staff_):
А зачем подчеркивание в is_staff?
В остальных тестах используется типипзация, а здесь почему-то нет.

2023-06-06 07:59 UTC, kirill-gorshkov commented on test/test_api.py
> +        user = User(username="test_user", password="pass", is_staff=is_staff_)
Зачем здесь задавать имя пользователя, если оно будет изменено впоследствии?

2023-06-06 07:59 UTC, kirill-gorshkov commented on test/test_tag.py
> +        return [{**attributes, "id": entities[0]["id"]}]
Этот метод - почти полное повторение предыдущего. Если ожидается список, в качестве expected_details, то можно сделать assert my_data == [self.expected_details]

2023-06-06 07:59 UTC, kirill-gorshkov commented on test/test_tag.py
> +        assert response == None
А зачем для этого отдельный вьюсет? Можно ведь все в прошлый засунуть

2023-06-06 07:59 UTC, kirill-gorshkov commented on test/test_task.py
> +    user_data = {
Не стоит называть одинаковые сущности разными именами. Лучше назвать user_attributes1, user_attributes2, ...

2023-06-06 07:59 UTC, kirill-gorshkov commented on test/test_task.py
> +            key: task[key] for key in ["id", "title", "description"]
А что возвращает task, что приходится так делать? Может, положить в expected_details дополнительные аттрибуты, которые мы ожидаем в таске?

2023-06-08 12:42 UTC, kirill-gorshkov requested changes
Все что я написал про тесты и сравнение request'а и response'а относится и к другим тестам

2023-06-08 12:42 UTC, kirill-gorshkov commented on main/serializers.py
> +    author = UserSerializer(required=False)  # for testing sake
Комментариев в коде быть не должно

2023-06-08 12:42 UTC, kirill-gorshkov commented on test/base.py
> +        self.client.logout()
Зачем каждый раз логаутиться? Зачем каждый раз логиниться?

2023-06-08 12:42 UTC, kirill-gorshkov commented on test/test_tag.py
> +        expected_response = self.expected_details(tags[0], self.tag_attributes)
Опять не то. Нужно создать теги, записать их в переменную, а потом сравнить с выдачей из list'а

2023-06-08 12:42 UTC, kirill-gorshkov commented on test/test_tag.py
> +        expected_response = self.expected_details(tag1, self.tag_attributes)
expected_response надо делать из tag, а не tag1. Мы сравниваем созданное с полученным

2023-06-08 12:42 UTC, kirill-gorshkov commented on test/test_tag.py
> +        self.user.is_staff = True
Нельзя менять аттрибуты класса в ходе каких-либо тестов, это может изменить результат других тестов.

2023-06-09 05:21 UTC, Jojobass commented on test/test_tag.py
> +        self.user.is_staff = True
нужно вернуть обратно в конце теста или поступить вообще по другому? Поэтому делал отдельный вьюсет, где с самого начала user_attributes с is_staff=True

2023-06-16 06:04 UTC, kirill-gorshkov approved these changes

2023-06-30 11:23 UTC, closed without merging