Feature/simplejwt tests
Jojobass/TaskManager pull request #18
Opened 2023-06-06 12:22 UTC by Jojobass

2023-06-06 14:40 UTC, kirill-gorshkov requested changes
Проверьте везде, где, что и с чем вы сравниваете при тестах. Очень много где объект сравнивается сам с собой

2023-06-06 14:40 UTC, kirill-gorshkov commented on main/views.py
> +    permission_classes = (IsStaffDeletePolicy, *api_settings.DEFAULT_PERMISSION_CLASSES)
А какие permission_classes содержит api_setting?

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/base.py
>      def create_api_user(cls):
А где типизация результата действия данного метода?

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_jwt.py
> +    """returns a random username"""
Комментариев быть не должно

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_jwt.py
> +class UserFactory(DjangoModelFactory):
Повторение кода

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_tag.py
> +        assert tags == [expected_response]
Получается, что мы берем тег из ответа, а потом сравниваем его с тегом из ответа?

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_tag.py
> +        expected_response = self.expected_details(tag, self.tag_attributes)
Получается, что сравниваем тег сам с собой. Нам нужен созданный тег

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_tag.py
>          assert tag == expected_response
Тоже самое

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_tag.py
> +        print(self.user.is_staff)
Принтов в репе быть не должно

2023-06-06 14:40 UTC, kirill-gorshkov commented on test/test_tag.py
>          assert response == None
А проверить статусный код?

2023-06-07 06:26 UTC, Jojobass commented on main/views.py
> +    permission_classes = (IsStaffDeletePolicy, *api_settings.DEFAULT_PERMISSION_CLASSES)
rest_framework.permissions.IsAuthenticated
надо его explicitly написать?
если его не указывать, то permission class не применяется, как я понял

2023-06-07 06:29 UTC, Jojobass commented on test/base.py
>      def create_api_user(cls):
согласен (в уроке его не было и это был staticmethod - для staticmethod можно не типизировать?)

2023-06-07 07:02 UTC, Jojobass commented on test/test_tag.py
> +        assert tags == [expected_response]
Не совсем понял. Создали тег, потом взяли список тегов (фильтруем по всем аттрибутам - получается список из одного только что созданного), ожидаем, что это будет список из одного тега с данными аттрибутами, проверили.
Делал по образцу. Укажите, как нужно, пожалуйста

2023-06-07 07:06 UTC, Jojobass commented on test/test_tag.py
> +        expected_response = self.expected_details(tag, self.tag_attributes)
Опять не понял. Положили тег в базу, взяли тег по id, ожидаем, что это тег с заданными аттрибутами, проверили.
Переименовать тег, который взяли в tag1 или tag_retrieved?

2023-06-07 07:13 UTC, Jojobass commented on test/test_tag.py
>          assert response == None
Это проверяется в TestViewSetBase.delete(), который возвращает Response.data

2023-06-07 07:23 UTC, kgorshkoff commented on test/test_tag.py
> +        assert tags == [expected_response]
Необходимо создать какой-то тег, потом запросить список всех тегов, а потом сравнить созданный тег со списком.
У вас получается мы создаем тег, потом получаем тег, и полученный тег сравниваем со списком полученных тегов.

2023-06-07 07:24 UTC, kgorshkoff commented on test/test_tag.py
> +        expected_response = self.expected_details(tag, self.tag_attributes)
Все так. При self.retrieve вы затираете данных из self.create, после чего сравниваете полученный тег с полученным тегом. 
Сравнивать надо данных из self.create с self.retrieve.

2023-06-07 07:40 UTC, kgorshkoff requested changes

2023-06-07 07:40 UTC, kgorshkoff commented on main/views.py
> +    permission_classes = (IsStaffDeletePolicy, *api_settings.DEFAULT_PERMISSION_CLASSES)
Там не IsAuthenticated. Внутрь кода, а так же библиотек в PyCharm (как я понимаю у вас он) можно "проваливаться" через cmd+click (ctrl + click на win/linux).

Залезьте внутрь api_settings и посмотрите, какие permission class'ы есть в настройках

2023-06-07 07:40 UTC, kgorshkoff commented on test/base.py
>      def create_api_user(cls):
Типизировать надо все, это ведь для своего удобства. 
Я вот по памяти, честно скажу, не вспомню что вернет UserFactory. Это может быть dict, это может быть объект. А ведь у них совсем разный доступ к аттрибутам.

Через пару недель уже и не вспомнится, какой метод что возвращает и тогда придется принтить или дебажить

2023-06-07 07:54 UTC, Jojobass commented on test/test_tag.py
> +        assert tags == [expected_response]
то есть без expected response, напрямую сущности сравнить? ОК

2023-06-07 07:55 UTC, Jojobass commented on test/test_tag.py
> +        expected_response = self.expected_details(tag, self.tag_attributes)
Только ведь сравниваю полученный тег не с полученным тегом, а с аттрибутами, с помощью которого создал первый. Но понял, переделаю

2023-06-07 08:13 UTC, Jojobass commented on test/test_tag.py
> +        assert tags == [expected_response]
не сущности, а словарь, который возвращает create() со словарем, который возвращает list()

2023-06-07 08:48 UTC, Jojobass commented on test/test_tag.py
> +        assert tags == [expected_response]
> Не совсем понял. Создали тег, потом взяли список тегов (фильтруем по всем аттрибутам - получается список из одного только что созданного), ожидаем, что это будет список из одного тега с данными аттрибутами, проверили. Делал по образцу. Укажите, как нужно, пожалуйста

не фильтруется там ничего)

2023-06-08 12:43 UTC, kirill-gorshkov approved these changes

2023-06-27 08:41 UTC, merged