Feature/serializers
Jojobass/TaskManager pull request #8
Opened 2023-05-24 13:44 UTC by Jojobass

2023-05-29 13:46 UTC, aleksandr-semenov-dbp requested changes

2023-05-29 13:46 UTC, aleksandr-semenov-dbp commented on main/serializers.py
> +    def create(self, validated_data):
в рамках этого урока давайте делать простые сериализаторы по аналогии с приведенным примером, пусть отрабатывает то, что должно автоматически отрабатывать, столько ручной работы пока не надо, в дальнейшем будет про вложенные серилизаторы.

2023-05-30 09:27 UTC, Jojobass commented on main/serializers.py
> +    def create(self, validated_data):
убрал, спасибо

2023-06-02 06:40 UTC, aleksandr-semenov-dbp approved these changes

2023-06-30 11:23 UTC, closed without merging