Feature/viewsets
Jojobass/TaskManager pull request #9
Opened 2023-05-26 06:46 UTC by Jojobass

2023-05-30 07:43 UTC, kirill-gorshkov requested changes

2023-05-30 07:43 UTC, kirill-gorshkov commented on main/serializers.py
> +    # def create(self, validated_data):
Мы не оставляем комментарии в коде. Если этот код когда-либо потребуется, его можно будет найти в git

2023-05-30 09:27 UTC, Jojobass commented on main/serializers.py
> +    # def create(self, validated_data):
спасибо, исправил

2023-06-02 06:43 UTC, aleksandr-semenov-dbp approved these changes

2023-06-30 11:23 UTC, closed without merging